"""Emit Microsoft Fabric / Power BI artifacts from the IR (lifecycle stage 3).

Outputs are text-based and diff-friendly, matching Power BI Project (.pbip)
conventions:
  model.tmdl    - tables, columns, calculated columns and measures (TMDL)
  measures.dax  - every converted measure, copy-paste ready
Returns a structured conversion log so stages 4-5 can validate and report.
A calc that aggregates becomes a measure; a row-level calc becomes a
calculated column - the same distinction Power BI itself enforces.
"""
from __future__ import annotations

from .dax_functions import AGGREGATES
from .dax_transpile import transpile
from .model import Workbook

_DT = {"real": "double", "integer": "int64", "string": "string",
       "date": "dateTime", "datetime": "dateTime", "boolean": "boolean",
       "unknown": "string"}


def _has_aggregate(formula: str) -> bool:
    up = formula.upper()
    return any(f"{fn}(" in up.replace(" ", "") for fn in AGGREGATES)


def _tmdl_name(name: str) -> str:
    """Quote a TMDL identifier if it contains spaces/specials."""
    if name and all(c.isalnum() or c == "_" for c in name):
        return name
    return f"'{name}'"


def convert(wb: Workbook) -> dict:
    # names of calc fields that become measures (aggregate-bearing)
    measure_names = {f.name for f in wb.calculated_fields
                     if f.formula and _has_aggregate(f.formula)}

    conversions: list[dict] = []
    tables: dict[str, dict] = {}

    for ds in wb.datasources:
        t = tables.setdefault(ds.table_name, {"columns": [], "calc_columns": [],
                                              "measures": []})
        for f in ds.fields:
            if not f.is_calculated:
                t["columns"].append((f.name, _DT.get(f.datatype, "string")))
                continue
            rec = {"name": f.name, "table": ds.table_name,
                   "formula": f.formula, "kind": None, "dax": None,
                   "status": "converted", "warnings": []}
            try:
                dax, warns = transpile(f.formula, ds.table_name, measure_names)
                rec["dax"] = dax
                rec["warnings"] = warns
                if warns:
                    rec["status"] = "review"
                if f.name in measure_names:
                    rec["kind"] = "measure"
                    t["measures"].append((f.name, dax))
                else:
                    rec["kind"] = "calculated_column"
                    t["calc_columns"].append((f.name, dax))
            except Exception as exc:                       # lex/parse failure
                rec["status"] = "failed"
                rec["warnings"] = [f"could not transpile: {exc}"]
            conversions.append(rec)

    return {"files": _render_files(wb, tables), "conversions": conversions,
            "measure_names": sorted(measure_names), "tables": tables}


def _render_files(wb: Workbook, tables: dict) -> dict[str, str]:
    tmdl: list[str] = [f"// Generated by BIForge from {wb.source_platform} "
                       f"workbook '{wb.name}'", ""]
    dax_lines: list[str] = [f"// Converted measures from '{wb.name}'", ""]

    for tname, t in tables.items():
        tmdl.append(f"table {_tmdl_name(tname)}")
        for cname, dtype in t["columns"]:
            tmdl.append(f"\tcolumn {_tmdl_name(cname)}")
            tmdl.append(f"\t\tdataType: {dtype}")
            tmdl.append("")
        for cname, dax in t["calc_columns"]:
            tmdl.append(f"\tcolumn {_tmdl_name(cname)} = {dax}")
            tmdl.append("")
        for mname, dax in t["measures"]:
            tmdl.append(f"\tmeasure {_tmdl_name(mname)} = {dax}")
            tmdl.append("")
            dax_lines.append(f"{mname} = {dax}")
            dax_lines.append("")
        tmdl.append("")

    return {"model.tmdl": "\n".join(tmdl) + "\n",
            "measures.dax": "\n".join(dax_lines) + "\n"}
